<h1><font color="red">Titulo</font></h1>
<table>
	<tr>
		<td><i>Célula(1,1)</i></td>
		<td><strong>Célula(1,2)</strong></td>
		<td>Célula(1,3)</td>
	</tr>
	<tr>
		<td><font color="red">Célula(2,1)</font></td>
		<td><a href="http://www.google.com">Célula(2,2)</a></td>
		<td>Célula(2,3)</td>
	</tr>
	<tr>
		<td>Célula(3,1)</td>
		<td>Célula(3,2)</td>
		<td>Célula(3,3)</td>
	</tr>
</table>
<div>
<div style="float:left;">Macarrão</div>
<div>Feijão</div>
</div>
