<div class="row container">
    <table id="bars" cellpadding="0" cellspacing="0" border="0" class="table table-bordered table-hover">
        <thead>
            <tr>
                <th>#</th>
                <th>Comentário</th>
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($bars as $bar): ?>
            <tr>
                <td><?= $bar->getId() ?></td>
                <td><?= $bar->getNome() ?></td>
                <td><?= $bar->getDescricao() ?></td>
            </tr>
            <?php endforeach; ?>
        </tbody>
        <tfoot>
            
        </tfoot>
    </table>
</div>
<?php 
    $this->headScript()
         ->appendFile($this->basePath() . '/recursos/vendor/datatables/js/jquery.dataTables.min.js')
         ->appendFile($this->basePath() . '/recursos/js/VnsJavascript/vns.datatables.jquery.js')
?>
<style type="text/css">
    /* Fix for Bootstrap 3 box-sizing */
    div.dataTables_wrapper,
    div.dataTables_wrapper *,
    div.dataTables_wrapper *:before,
    div.dataTables_wrapper *:after {
        -webkit-box-sizing: content-box;
        -moz-box-sizing: content-box;
        box-sizing: content-box;
    }
</style>
<script type="text/javascript">
    $(document).ready(function() {
        var dtTableManager = new DataTableManager();
        var coldefs = [
             { "bVisible":    true,    "aTargets": [ 0 ] }  // Define quais colunas nao sao visiveis - codigo
            ,{ "sWidth":      "75px",   "aTargets": [ 0 ] }  // Define largura das colunas
            ,{ "sClass":      "center", "aTargets": [ 1 ] }  // Centraliza as colunas
        ]
        dtTableManager.createDatatable($('.table'),coldefs);
    });
</script>
