<div class="row container">
    <h1>Experimentos Gerais</h1>
    <hr/>
    <div class="row container">
        <div class="col-md-4">
            <h2>Base64 Encode of 1x1px Transparent GIF</h2>
            <ul>
                <li><img src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7"></li>
                <li><img src="data:image/gif;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs="></li>
            </ul>
        </div>
        <div class="col-md-4">
            <h2>Helvetica</h2>
            <p class="helvetica text-justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget lacus tristique, interdum ante eget, placerat felis. 
                Donec imperdiet, erat vel elementum semper, orci purus consectetur turpis, sed porttitor ligula odio a augue. Vivamus 
                eleifend ante nec mi vestibulum ultrices. Etiam mauris massa, lobortis in est sit amet, sagittis dapibus risus. 
                Praesent ultrices viverra est quis feugiat. Duis scelerisque enim condimentum, imperdiet velit ac, egestas ante. 
                Maecenas condimentum nunc ac nisl suscipit, volutpat sodales velit pretium. Mauris dictum vulputate libero molestie 
                pretium. Curabitur pharetra porta lorem, ac interdum dui pulvinar vitae.
            </p>
            <h2>Better Helvetica</h2>
            <p class="better-helvetica text-justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam eget lacus tristique, interdum ante eget, placerat felis. 
                Donec imperdiet, erat vel elementum semper, orci purus consectetur turpis, sed porttitor ligula odio a augue. Vivamus 
                eleifend ante nec mi vestibulum ultrices. Etiam mauris massa, lobortis in est sit amet, sagittis dapibus risus. 
                Praesent ultrices viverra est quis feugiat. Duis scelerisque enim condimentum, imperdiet velit ac, egestas ante. 
                Maecenas condimentum nunc ac nisl suscipit, volutpat sodales velit pretium. Mauris dictum vulputate libero molestie 
                pretium. Curabitur pharetra porta lorem, ac interdum dui pulvinar vitae.
            </p>
        </div>
        <div class="col-md-4">
            <h2>Gradiente</h2>
            <div class="gradiente" style="height: 200px; width: 300px;">
                <p class="text-center">Div com gradiente</p>
            </div>
            <h2>Gradiente no padding</h2>
            <div class="gradiente padding-colorido" style="height: 200px; width: 300px;">
                <p class="text-center">Div com gradiente no padding</p>
            </div>
        </div>
    </div>
    <div class="row container">
        <div class="col-md-4">
            <h2>Padding colorido</h2>
            <div class="padding-colorido" style="height: 300px; width: 300px;">
                <p class="text-center">Div branca com padding cinza</p>
            </div>
        </div>
        <div class="col-md-4">
            <h2>Padding colorido 2</h2>
            <div class="padding-colorido-dois" style="height: 300px; width: 300px;">
                <p class="text-center">Div amarela com padding vermelho</p>
            </div>
        </div>
        <div class="col-md-4">
            <h2>Padding colorido 3</h2>
            <div class="padding-colorido-tres" style="height: 300px; width: 300px;">
                <p class="text-center">Div branca com padding preto</p>
            </div>
        </div>
    </div>
</div>
<style type="text/css">
    /* Font Helvetica */
    .helvetica {
        font-family: Helvetica, Arial, "Lucida Grande", sans-serif; 
    }
    /* Font Helvetica mais bonita */
    .better-helvetica {
        font-family: "HelveticaNeue-Light", "Helvetica Neue Light", "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif; 
        font-weight: 300;
    }
    
    /* Linear Gradient no IE9, IE8 e IE7 */
    .gradiente {
        background: #fff;
        background: -moz-linear-gradient(#C0C0C0, #FFFFFF);
        background: -webkit-linear-gradient(#C0C0C0, #FFFFFF);
        background: -o-linear-gradient(#C0C0C0, #FFFFFF);
        background: -ms-linear-gradient(#C0C0C0, #FFFFFF);/*For IE10*/
        background: linear-gradient(#C0C0C0, #FFFFFF);
        filter: progid:DXImageTransform.Microsoft.gradient(GradientType=0,startColorstr='#C0C0C0', endColorstr='#FFFFFF');/*For IE7-8-9*/ 
        height: 1%;/*For IE7*/ 
    }
    
    /**
     * Criar uma div com pading em outra cor
     */
    /* Primeira solucao */
    .padding-colorido {
        margin:0px auto;
        width:100%;
        height:50px;
        background-color:grey;
        float:left;
        padding:10px;
        position: relative;
        z-index: 10;
    }
    .padding-colorido:after {
        background-color: white;
        content: '';
        display: block;
        position: absolute;
        top: 10px;
        left: 10px;
        right: 10px;
        bottom: 10px;
        z-index: -1;
    }
    /* Segunda solucao */
    .padding-colorido-dois {
        padding:10px;
        background-image:linear-gradient(to bottom, rgba(240, 255, 40, 1) 0%, rgba(240, 255, 40, 1) 100%), linear-gradient(to bottom, rgba(240, 40, 40, 1) 0%, rgba(240, 40, 40, 1) 100%);
        background-clip: content-box, padding-box;
    }
    /* Terceira solucao */
    .padding-colorido-tres {
        padding: 10px;
        background-image: 
            -moz-linear-gradient(top, #000 10px, transparent 10px),
            -moz-linear-gradient(bottom, #000 10px, transparent 10px),
            -moz-linear-gradient(left, #000 10px, transparent 10px),
            -moz-linear-gradient(right, #000 10px, transparent 10px);
        background-image: 
            -o-linear-gradient(top, #000 10px, transparent 10px),
            -o-linear-gradient(bottom, #000 10px, transparent 10px),
            -o-linear-gradient(left, #000 10px, transparent 10px),
            -o-linear-gradient(right, #000 10px, transparent 10px);
        background-image: 
            -webkit-linear-gradient(top, #000 10px, transparent 10px),
            -webkit-linear-gradient(bottom, #000 10px, transparent 10px),
            -webkit-linear-gradient(left, #000 10px, transparent 10px),
            -webkit-linear-gradient(right, #000 10px, transparent 10px);
        background-image: 
            linear-gradient(top, #000 10px, transparent 10px),
            linear-gradient(bottom, #000 10px, transparent 10px),
            linear-gradient(left, #000 10px, transparent 10px),
            linear-gradient(right, #000 10px, transparent 10px);
    }
</style>