<?php foreach(range(0, 3) as $p): ?>
<div id="texto-um" class="text-justify">
    <h4>O Desenvolvimento das Placas Sedimentares</h4>
    <p>
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec vitae enim at erat euismod tincidunt ut eu justo. Integer ut velit dictum quam faucibus iaculis quis sit amet ipsum. Suspendisse malesuada vel mi a laoreet. Sed ac turpis ac odio tempor bibendum. Proin blandit eros eu accumsan hendrerit. Aliquam neque arcu, mollis ac sapien a, luctus ultricies metus. Aenean et nulla ligula. In consequat in justo ut ultricies.
    </p>
    <p>
    Donec id ipsum vel metus placerat ornare vitae ut velit. Vestibulum a placerat orci, at hendrerit massa. Praesent eu lectus rhoncus, venenatis augue sed, iaculis ligula. Cras laoreet id eros id semper. Pellentesque vestibulum ultricies cursus. Integer in nulla at ligula rutrum convallis a ut mi. Curabitur sit amet semper leo. Nulla vel sem ac nisl vehicula vulputate. Phasellus id ultrices erat. Morbi pretium augue ut quam congue, ut convallis erat pulvinar. Pellentesque ultrices luctus odio ac sodales. Quisque consequat, leo sed interdum pellentesque, turpis metus hendrerit tortor, sed consequat velit mi in urna. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;
    </p>
    <p>
    Praesent ornare massa commodo, blandit turpis vitae, suscipit metus. Morbi malesuada ante nec dolor aliquam, non imperdiet risus consequat. Quisque varius sapien sed quam varius, in tristique nisi facilisis. Aliquam elementum, sapien ut semper euismod, lectus urna dignissim nibh, vitae sodales libero urna sit amet velit. Nunc a magna enim. Aliquam volutpat ornare metus eget adipiscing. Interdum et malesuada fames ac ante ipsum primis in faucibus.
    </p>
    <p>
    Donec consectetur rhoncus elit a ultrices. Aliquam sit amet lacus ullamcorper, malesuada tellus eget, lacinia arcu. Suspendisse nunc enim, auctor gravida vulputate sit amet, facilisis ut tellus. Sed dapibus eget nunc scelerisque accumsan. Praesent rutrum lobortis neque, eu lobortis libero rutrum eu. Integer dictum nec urna in pulvinar. Integer ut purus ac odio interdum sollicitudin. Aliquam nisi ipsum, auctor at placerat vitae, hendrerit non nibh. Proin viverra elit at tellus lacinia, sit amet accumsan tortor hendrerit. Nam pellentesque tellus at lectus varius, ac tincidunt dolor iaculis.
    </p>
    <p>
    Aliquam eros erat, faucibus non lacinia gravida, ultrices ac orci. Suspendisse risus ante, venenatis id vulputate eu, mollis et tortor. Pellentesque sed lectus vel orci pulvinar pulvinar ut sit amet turpis. Morbi tristique venenatis lacus sit amet ultrices. Nulla vitae urna cursus, volutpat lacus et, venenatis orci. In blandit tempor metus. Nam volutpat odio nec pulvinar pretium. Nulla tempor malesuada suscipit. Proin vitae sodales justo, id ornare lectus. Curabitur imperdiet mattis lacinia. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at vulputate justo. In metus ipsum, tincidunt et lectus semper, rhoncus egestas metus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; 
    </p>
    <small>Fonte: Dr. Rodrigo de Freitas Santos</small>
</div>
<?php endforeach; ?>

