<?php echo $this->doctype(); ?>

<html lang="pt-BR">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('VNS Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/recursos/img/storms.ico'))
                        ->prependStylesheet($this->basePath() . '/recursos/css/stickyfooter.css')
                        ->prependStylesheet($this->basePath() . '/recursos/css/style.css')
						->prependStylesheet($this->basePath() . '/recursos/vendor/bootswatch/united/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/recursos/vendor/bootstrap/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/recursos/vendor/bootstrap/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/recursos/vendor/jquery/jquery.min.js')
            ->prependFile($this->basePath() . '/recursos/vendor/respond/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/recursos/vendor/html5shiv/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>
    </head>
    <body>
        <!-- Wrap all page content here -->
        <div id="wrap" class="container">
            <!-- Begin page navigation -->
            <nav id="nav-container" class="navbar navbar-default container" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="navbar-brand" href="<?php echo $this->url('home') ?>">
                        <img src="<?php echo $this->basePath('/recursos/img/logo/vns-logo.png') ?>" alt="VNS Desenvolvimento"/>&nbsp;</a>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav">
                            <li class="<?php echo ($this->url() == '/')?'active':'' ?>">
                                <a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a>
                            </li>
                            <li class="<?php echo ($this->url() == '/vnsexperimental')?'active':'' ?>">
                                <a href="<?php echo $this->url('vnsexperimental') ?>"><?php echo $this->translate('Experimentos') ?></a>
                            </li>
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </nav>
            <!-- Begin page content -->
            <div id="main-container" class="container">
                <?php echo $this->content; ?>
            </div>
        </div>
        <!-- Begin page footer -->
        <footer id="footer" class="container">
            <div class="container">
                <p>&copy; 2012 - <?php echo date('Y') ?> por <strong>Vinicius Oliveira Garcia</strong> - <?php echo $this->translate('All rights reserved') ?>.</p>
                <div id="logo-storms">
                    <a href="http://www.storms.com.br">
                        <div class="a"></div>
                    </a>
                </div>
            </div>
        </footer>
        <?php echo $this->inlineScript() ?>
    </body>
</html>
