<div class="row container">
    <h1>Experimentos Gerais</h1>
    <hr/>
    <div class="row">
        <div class="col-md-4">
            <h2>Experimentos</h2>
            <ul>
                <li>Componentes
                    <ul>
                        <li><a href="<?php echo $this->url('vnsexperimental', array('controller' => 'pdf', 'action' => 'index')) ?>"><?php echo $this->translate('DOM PDF') ?></a></li>
                        <li><a href="<?php echo $this->url('vnsexperimental', array('controller' => 'excel', 'action' => 'index')) ?>"><?php echo $this->translate('PHP Excel') ?></a></li>
                        <li><a href="<?php echo $this->url('vnsexperimental', array('controller' => 'tabela', 'action' => 'index')) ?>"><?php echo $this->translate('Jquery DataTables') ?></a></li>
                        <li><a href="<?php echo $this->url('vnsexperimental', array('controller' => 'form', 'action' => 'index')) ?>"><?php echo $this->translate('Jquery Form - Pendente') ?></a></li>
                    </ul>
                </li>
                <li>Doctrine 2
                    <ul>
                        <li><a href="<?php echo $this->url('vnsexperimental', array('controller' => 'doctrine', 'action' => 'index')) ?>"><?php echo $this->translate('Classe Foo') ?></a></li>
                        <li><a href="<?php echo $this->url('vnsexperimental', array('controller' => 'doctrine', 'action' => 'bar')) ?>"><?php echo $this->translate('Classe Bar') ?></a></li>
                    </ul>
                </li>
                <li>Outros experimentos
                    <ul>
                        <li><a href="<?php echo $this->url('vnsexperimental', array('controller' => 'twtform', 'action' => 'index')) ?>"><?php echo $this->translate('Twitter Bootstrap Form - Não Funciona') ?></a></li>
                        <li><a href="<?php echo $this->url('vnsexperimental', array('controller' => 'twtmodule', 'action' => 'index')) ?>"><?php echo $this->translate('Módulo Twitter Bootstrap - Não Funciona') ?></a></li>

                        <li><a href="<?php echo $this->url('vnsexperimental', array('controller' => 'css-tricks', 'action' => 'index')) ?>"><?php echo $this->translate('CSS Tricks') ?></a></li>
                        <li><a href="<?php echo $this->url('vnsexperimental', array('controller' => 'estilo', 'action' => 'index')) ?>"><?php echo $this->translate('Estilos com Texto') ?></a></li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="col-md-4">
            <h2>Lembretes</h2>
            <ul>
                <li>Componentes que pretendemos criar
                    <ul>
                        <li>Forms com Twitter Bootstrap 3;</li>
                        <li>CRUD;</li>
                        <li>Dependent DropDown;</li>
                        <li>Alerts/Modals;</li>
                        <li>Upload de Imagens;</li>
                    </ul>
                </li>
                <li>Componentes que precisamos testar
                    <ul>
                        <li>ZfcAdmin - Interface comum p/ áreas de admin;</li>
                        <li>ZfcUser - Autenticação;</li>
                        <li>BjyAuthorize - Permissões;</li>
                        <li>ScnSocialAuth - Autenticação com redes sociais;</li>
                    </ul>
                </li>
            </ul>
        </div>
        <div class="col-md-4">
            <h2>JavaScript</h2>
            <ul>
                <li>Testar o General;</li>
                <li>Testar o Json;</li>
                <li>Testar o EqualHeights;</li>
                <li>Testar o PlaceHolder;</li>
                <li>Testar o Alert do Bootstrap;</li>
                <li>Testar o Jquery UI;</li>
                <li>Testar o FineUploader;</li>
                <li>Testar o FormPlugin;</li>
                <li>Testar o FormatCurrency;</li>
                <li>Testar o MaskMoney;</li>
                <li>Testar o Redirect;</li>
                <li>Testar o CameraSlideshow;</li>
                <li>Testar o DependentDropdown;</li>
                <li>Testar o BlockUi;</li>
            </ul>
        </div>
    </div>
</div>
